### ISSUE TITLE
Litecoin Scrypt API

### ISSUE THREAD

**Issue by nodecode** [bitpay/insight-ui#525]
An API for Scrypt-based cryptocurrencies such as Litecoin would be great.

**Comment by genecyber** [comment]
Changing ports will not magically make alternate hashing algo's pop up in code. 

So the problem here is simple, insight was made for Bitcoin and is a sha256 coin. The error described amongst a few threads all with differing coin hashing algo's likely all suffer the same problem. 
This line here in "insight-bitcore-api/lib/peer sync.js".

var blockHash = bitcoreUtil.formatHashFull(block.calcHash())

Looking deeper we find a hard coded reference to sha256 hashing. Which of course won't return a valid block hash on say a sCrypt block.

My quick fix to remedy this temporarily is to look for malformed hashed (no leading zeros) and fall back to RPC which naturally works because the altcoin daemons are using the correct algo to parse and store blocks.

See the patch here https://gist.github.com/genecyber/46a835038221d8e30cfb

Note: the block reader that's reads from disk also has a similar issue but hey... Teach a man to fish and all...

**Comment by doged** [comment]
@genecyber does that replace 85-102? or just replace 85?
