### ISSUE TITLE
Previous TIP is now orphan. Back to:undefined

### ISSUE THREAD

**Issue by saymissme** [bitpay/insight-ui#558]
I was installed the insight-api
set network.js config.js
then insight-api is working good

but a moment
when a new block was be found
show me this error
<code>
info: Previous TIP is now orphan. Back to:undefined
</code><code>
/root/insight-api/lib/BlockDb.js:119
     throw new Error('unable to get info for block:'+ hash);
           ^
Error: unable to get info for block:5f6cfa27fe98da0523fb84afed5b98275feab5f0a0803b472bf25c08eb840
    at /root/insight-api/lib/BlockDb.js:119:12
    at /root/insight-api/lib/BlockDb.js:280:30
    at /root/insight-api/lib/Rpc.js:88:40
    at IncomingMessage.<anonymous> (/root/insight-api/node_modules/bitcore/lipcClient.js:203:7)
    at IncomingMessage.emit (events.js:117:20)
    at _stream_readable.js:943:16
    at process._tickCallback (node.js:419:13)
[nodemon] app crashed - waiting for file changes before starting...
</code>

My wallet is working fine
no orphan blocks

if i change the magic in network.js
cant connected to my P2P port
api and web will working
but web homepage cant auto update

my coin is a scrypt altcoin
how to fix it?
THX

**Comment by genecyber** [comment]
So the problem here is simple, insight was made for Bitcoin and is a sha256 coin. The error described amongst a few threads all with differing coin hashing algo's likely all suffer the same problem. 
This line here in "insight-bitcore-api/lib/peer sync.js".

var blockHash = bitcoreUtil.formatHashFull(block.calcHash())

Looking deeper we find a hard coded reference to sha256 hashing. Which of course won't return a valid block hash on say a sCrypt block.

My quick fix to remedy this temporarily is to look for malformed hashed (no leading zeros) and fall back to RPC which naturally works because the altcoin daemons are using the correct algo to parse and store blocks.

See the patch here https://gist.github.com/genecyber/46a835038221d8e30cfb

Note: the block reader that's reads from disk also has a similar issue but hey... Teach a man to fish and all...
